# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Linux
  pool:
    vmImage: "ubuntu-16.04"
  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: ".."
  - task: CMake@1
    inputs:
      cmakeArgs: "--build ."

- job: Windows
  pool:
    vmImage: "vs2017-win2016"
  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: ".."
  - task: CMake@1
    inputs:
      cmakeArgs: "--build ."

- job: macOS
  pool:
    vmImage: "macOS-10.13"
  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: ".."
  - task: CMake@1
    inputs:
      cmakeArgs: "--build ."
