[package]
name = "altac"
version = "0.1.0"
authors = ["Ariel Abreu <facekapow@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
